"use client";

import { useEffect, useRef, useState } from "react";
import { CheckCircle2, ClipboardCheck, Clock3, Send, TimerReset } from "lucide-react";
import { Button } from "@/components/ui/button";

type Exam = { id: string; title: string; duration_seconds: number; question_count: number; completed: number };
type Question = { id: string; question: string; options: string[] };
type ExamPayload = { error?: string; exams?: Exam[]; exam?: Exam; attemptId?: string; startedAt?: string; questions?: Question[]; score?: number; totalPoints?: number; durationSeconds?: number; percentage?: number };

export function McqExamView() {
  const [exams, setExams] = useState<Exam[]>([]); const [active, setActive] = useState<{ exam: Exam; attemptId: string; questions: Question[]; started: number } | null>(null); const [remainingSeconds, setRemainingSeconds] = useState(0);
  const [answers, setAnswers] = useState<Record<string, number>>({}); const answersRef = useRef<Record<string, number>>({}); const [result, setResult] = useState<Record<string, number> | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const load = async () => { const response = await fetch("/api/exams", { cache: "no-store" }); const payload = await response.json() as ExamPayload; if (!response.ok) { setError(payload.error ?? "Could not load exams."); return; } setExams(payload.exams ?? []); };
  useEffect(() => { load(); }, []);
  const start = async (exam: Exam) => { setError(""); const response = await fetch("/api/exams", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "start", examId: exam.id }) }); const payload = await response.json() as ExamPayload; if (!response.ok || !payload.exam || !payload.attemptId || !payload.questions || !payload.startedAt) { setError(payload.error ?? "Could not start exam."); return; } answersRef.current = {}; setAnswers({}); setResult(null); setActive({ exam: payload.exam, attemptId: payload.attemptId, questions: payload.questions, started: Date.parse(payload.startedAt) }); };
  const submit = async () => { if (!active || loading) return; setLoading(true); const response = await fetch("/api/exams", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "submit", examId: active.exam.id, attemptId: active.attemptId, answers: Object.entries(answersRef.current).map(([questionId, selectedOption]) => ({ questionId, selectedOption })) }) }); const payload = await response.json() as ExamPayload; setLoading(false); if (!response.ok || payload.score === undefined || payload.totalPoints === undefined || payload.durationSeconds === undefined || payload.percentage === undefined) { setError(payload.error ?? "Could not submit exam."); return; } setResult({ score: payload.score, totalPoints: payload.totalPoints, durationSeconds: payload.durationSeconds, percentage: payload.percentage }); setActive(null); await load(); };
  useEffect(() => { if (!active) return; let expired = false; const update = () => { const remaining = Math.max(0, Math.ceil((active.started + active.exam.duration_seconds * 1000 - Date.now()) / 1000)); setRemainingSeconds(remaining); if (remaining === 0 && !expired) { expired = true; void submit(); } }; update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, [active]);
  if (active) return <section className="panel exam-stage"><div className="panel-head"><div><p className="eyebrow"><ClipboardCheck /> MCQ assessment</p><h2>{active.exam.title}</h2></div><span className={remainingSeconds <= 60 ? "exam-time-warning" : ""}><Clock3 /> {Math.floor(remainingSeconds / 60)}:{String(remainingSeconds % 60).padStart(2, "0")} remaining</span></div>{active.questions.map((question, index) => <fieldset className="exam-question" key={question.id}><legend>{index + 1}. {question.question}</legend>{question.options.map((option, optionIndex) => <label key={optionIndex}><input type="radio" name={question.id} checked={answers[question.id] === optionIndex + 1} onChange={() => { answersRef.current = { ...answersRef.current, [question.id]: optionIndex + 1 }; setAnswers((current) => ({ ...current, [question.id]: optionIndex + 1 })); }} />{option}</label>)}</fieldset>)}<Button onClick={submit} disabled={loading || remainingSeconds === 0}>{loading ? "Submitting…" : remainingSeconds === 0 ? "Submitting…" : "Submit assessment"} <Send /></Button></section>;
  return <><section className="section-title"><div><p className="eyebrow"><ClipboardCheck /> Timed assessment</p><h1>MCQ Exams</h1><p>Complete your assigned assessment once. Your facilitator will see the final report.</p></div><TimerReset /></section>{error && <p className="login-error">{error}</p>}{result && <section className="panel exam-result"><CheckCircle2 /><h2>Assessment submitted</h2><strong>{result.percentage}%</strong><p>{result.score} / {result.totalPoints} points • {result.durationSeconds} seconds</p></section>}<div className="exam-list">{exams.map((exam) => <article className="panel exam-card" key={exam.id}><div><span className="eyebrow">{exam.question_count} questions</span><h2>{exam.title}</h2><p>{Math.ceil(exam.duration_seconds / 60)} minute limit</p></div><Button onClick={() => start(exam)} disabled={Boolean(exam.completed)}>{exam.completed ? "Completed" : "Start exam"}</Button></article>)}{!exams.length && <div className="empty-state"><ClipboardCheck /><h2>No assessments assigned</h2><p>Your facilitator will assign an exam to your learner batch.</p></div>}</div></>;
}
